name: Tests

on:
  pull_request: null
  push:
    branches:
      - "main"

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-main"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3-php-versions:
          - { typo3: 13, php: 8.2 }

    name: "Run tests with PHP ${{ matrix.typo3-php-versions.php }} using TYPO3 ${{ matrix.typo3-php-versions.typo3 }}"
    steps:
      -   uses: actions/checkout@v4

      -   uses: shivammathur/setup-php@v2
          with:
            php-version: "${{ matrix.typo3-php-versions.php }}"
            extensions: intl, mbstring, pdo_sqlite, pdo_mysql
            coverage: none
          env:
            COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # see https://github.com/ramsey/composer-install
      -   uses: "ramsey/composer-install@v2"

      - name: "Run Unit tests"
        run: composer test-unit

      - name: "Functional tests"
        run: |
          export typo3DatabaseName="typo3";
          export typo3DatabaseHost="127.0.0.1";
          export typo3DatabaseUsername="root";
          export typo3DatabasePassword="root";
          composer test-functional
